// Site
export const SITE_LOADING = 'SITE_LOADING';
export const SITE_LOADED = 'SITE_LOADED';
export const SET_SIDEBAR_TOGGLER = 'SET_SIDEBAR_TOGGLER';

// Auth
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL'
export const ACTIVATING_USER = 'ACTIVATING_USER';
export const USER_ACTIVATED = 'USER_ACTIVATED';
export const ACTIVATION_FAILED = 'ACTIVATION_FAILED';

export const SOCIAL_AUTH_SUCCESS = 'SOCIAL_AUTH_SUCCESS';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const USER_UPDATED = 'USER_UPDATED';
export const UPDATE_ERROR = 'UPDATE_ERROR';
export const AUTH_ERROR = 'AUTH_ERROR';

export const REQUEST_LOADING = 'REQUEST_LOADING';
export const PASSWORD_UPDATE = 'PASSWORD_UPDATE';
export const REQUEST_PROCESSED = 'REQUEST_PROCESSED';

export const ADDRESS_ADDED = 'ADDRESS_ADDED';
export const ADDRESS_DELETED = 'ADDRESS_DELETED';
export const ADDRESS_UPDATED = 'ADDRESS_UPDATED';

// Auth - Verification
export const VERIFYING_PASSWORD_RESET = 'VERIFYING_PASSWORD_RESET';
export const VERIFIED_PASSWORD_RESET = 'VERIFIED_PASSWORD_RESET';
export const PASSWORD_RESET_VERIFICATION_ERROR = 'PASSWORD_RESET_VERIFICATION_ERROR';
export const PASSWORD_RESET_DONE = 'PASSWORD_RESET_DONE';

// Admin
export const GET_ORDER_ITEMS = 'GET_ORDER_ITEMS';
export const ORDER_ITEMS_ERROR = 'ORDER_ITEMS_ERROR';

export const MANAGER_ORDER_LOADING = 'MANAGER_ORDER_LOADING';
export const GET_MANAGER_ORDER = 'GET_ORDER';
export const MANAGER_ORDER_ERROR = 'ORDER_ERROR';
export const REVIEW_ORDER = 'REVIEW_ORDER';

export const ORDER_ITEM_LOADING = 'ORDER_ITEM_LOADING';
export const GET_ORDER_ITEM = 'GET_ORDER_ITEM';
export const ORDER_ITEM_ERROR = 'ORDER_ITEM_ERROR';
export const REVIEW_PRODUCT = 'REVIEW_PRODUCT';
export const REVIEW_PRODUCT_ORDER = 'REVIEW_PRODUCT_ORDER';

export const MANAGER_ORDERS_LOADING = 'MANAGER_ORDERS_LOADING';
export const GET_MANAGER_ORDERS = 'GET_MANAGER_ORDERS';
export const MANAGER_ORDERS_ERROR = 'MANAGER_ORDERS_ERROR';

export const CLAIM_ORDER = 'CLAIM_ORDER';
export const RIDER_CANCEL_ORDER = 'RIDER_CANCEL_ORDER';
export const RIDER_UNCLAIM_ORDER = 'RIDER_UNCLAIM_ORDER';
export const PREPARE_ORDER = 'PREPARE_ORDER';

export const DELIVER_ORDER_ITEM = 'DELIVER_ORDER_ITEM';
export const DELIVER_ORDER = 'DELIVER_ORDER';

export const PICKUP_ORDER_ITEM = 'PICKUP_ORDER_ITEM';
export const PICKUP_ORDER = 'PICKUP_ORDER';

export const TOGGLING_IS_PUBLISHED = 'TOGGLING_IS_PUBLISHED';
export const TOGGLED_IS_PUBLISHED = 'TOGGLED_IS_PUBLISHED';
export const IS_PUBLISHED_ERROR = 'IS_PUBLISHED_ERROR';

export const SYNC_ORDER = 'SYNC_ORDER';
export const NEW_ORDER_UPDATE = 'NEW_ORDER_UPDATE';
export const MARK_ORDER = 'MARK_ORDER';